name: lint
on: push
jobs:
  check-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install-make
        run: sudo apt install make
      - name: install-packages
        run: npm ci
      - name: lint
        run: make lint